AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instance'
  SubnetId:
    Type: 'AWS::EC2::Subnet::Id'
    Description: 'ID of the existing subnet where the instance will be launched'
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  EbsVolumeSize:
    Type: Number
    Default: 8
    Description: 'Size of the EBS volume in GiB'
  AdditionalVolumeSize:
    Type: Number
    Default: 20
    Description: 'Size of the additional EBS volume in GiB'

Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: 'ami-0c7217cdde317cfec'  # Replace with your desired AMI ID
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref EbsVolumeSize
        - DeviceName: "/dev/sdb"
          Ebs:
            VolumeSize: !Ref AdditionalVolumeSize
      SecurityGroupIds:
        - 'sg-010f7a25dfa201718'  # Replace with your existing security group ID

Outputs:
  InstanceId:
    Description: 'Instance ID of the newly created EC2 instance'
    Value: !Ref MyInstance
