AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: 'ID of the existing VPC'

Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow SSH and HTTP traffic'
      VpcId: !Ref VpcId  
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'  
        - IpProtocol: 'tcp'
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'  

Outputs:
  SecurityGroupId:
    Description: 'ID of the newly created security group'
    Value: !Ref MySecurityGroup
